language: c
install: make get-deps
script : if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then cd projects && make ; fi

notifications:
  irc:
    channels: "irc.psas.pdx.edu#psas"
    template:
      - "%{repository}@%{branch}: %{message} (%{build_url})"
    on_success: change
    on_failure: change
    use_notice: true
  email: false

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "keQ+7ZLeN6bB0XonST9pitc4dMoZmuNV61Zs4aaCtYLHO9eMCfWe7GvKnBkh/XpKzJ6NGUiKk5lUaZH+BqMQuIDz/lOr4Ssv+vZOY582vQGyJC6mBCnQy0cgUzzTxew+Qa/fMSDmM4Fff98wkKJ7LxZFCTBKCayGoW6QMaG3CLY="

addons:
  coverity_scan:
    project:
      name: "psas/stm32"
      description: "Your project description here"
    notification_email: theo0x48@gmail.com
    build_command_prepend:
    build_command: "cd projects && make"
    branch_pattern: coverity_scan
